import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { unlinkSync } from 'node:fs';

import { ConfigSchema } from '../config/schema.js';
import type { ShadowConfig } from '../config/schema.js';
import { ShadowDatabase } from '../storage/database.js';
import { backfillEmbeddings } from './lifecycle.js';

function createTestDb(): { db: ShadowDatabase; cleanup: () => void; dbPath: string } {
  const dbPath = join(tmpdir(), `shadow-lifecycle-test-${randomUUID()}.db`);
  const parsed = ConfigSchema.parse({});
  const config: ShadowConfig = {
    ...parsed,
    resolvedDataDir: tmpdir(),
    resolvedDatabasePath: dbPath,
    resolvedArtifactsDir: join(tmpdir(), 'artifacts'),
  };
  const db = new ShadowDatabase(config);
  return {
    db,
    dbPath,
    cleanup: () => {
      db.close();
      try { unlinkSync(dbPath); } catch {}
      try { unlinkSync(dbPath + '-wal'); } catch {}
      try { unlinkSync(dbPath + '-shm'); } catch {}
    },
  };
}

function vectorExistsFor(db: ShadowDatabase, table: string, id: string): boolean {
  const row = db.rawDb.prepare(`SELECT id FROM ${table} WHERE id = ?`).get(id);
  return !!row;
}

describe('lifecycle.backfillEmbeddings', () => {
  let db: ShadowDatabase;
  let cleanup: () => void;

  before(() => {
    ({ db, cleanup } = createTestDb());
  });
  after(() => cleanup());

  it('backfills a memory created without an embedding', async () => {
    const mem = db.createMemory({
      layer: 'hot',
      scope: 'global',
      kind: 'taught',
      title: 'async writes are non-blocking',
      bodyMd: 'embedding is generated by periodic backfill, not inline in teach()',
      tags: ['async', 'memory'],
      sourceType: 'mcp',
    });

    assert.equal(vectorExistsFor(db, 'memory_vectors', mem.id), false, 'memory should not have embedding yet');

    const counts = await backfillEmbeddings(db);
    assert.ok(counts.memories >= 1, `expected memories backfill >= 1, got ${counts.memories}`);
    assert.equal(vectorExistsFor(db, 'memory_vectors', mem.id), true, 'memory vector should exist after backfill');
  });

  it('skips memories that already have an embedding (idempotent)', async () => {
    const counts = await backfillEmbeddings(db);
    assert.equal(counts.memories, 0, 'second run should be a no-op for memories');
  });

  it('processes multiple memories in a single pass', async () => {
    const ids: string[] = [];
    for (let i = 0; i < 3; i++) {
      const mem = db.createMemory({
        layer: 'hot',
        scope: 'global',
        kind: 'taught',
        title: `batch memory ${i}`,
        bodyMd: `body ${i}`,
        tags: [],
        sourceType: 'mcp',
      });
      ids.push(mem.id);
    }

    const counts = await backfillEmbeddings(db);
    assert.equal(counts.memories, 3, `expected 3 backfilled, got ${counts.memories}`);
    for (const id of ids) {
      assert.equal(vectorExistsFor(db, 'memory_vectors', id), true, `memory ${id} should have embedding`);
    }
  });
});
