export { ShadowDatabase, createDatabase } from './database.js';
export type {
  CreateProjectInput,
  CreateRepoInput,
  CreateSystemInput,
  CreateContactInput,
  CreateMemoryInput,
  CreateObservationInput,
  CreateSuggestionInput,
  CreateRunInput,
  CreateAuditEventInput,
  CreateLlmUsageInput,
} from './database.js';
export type {
  EntityLink,
  ProjectRecord,
  RepoRecord,
  SystemRecord,
  ContactRecord,
  UserProfileRecord,
  MemoryRecord,
  MemorySearchResult,
  ObservationRecord,
  SuggestionRecord,
  InteractionRecord,
  EventRecord,
  RunRecord,
  AuditEventRecord,
  LlmUsageRecord,
} from './models.js';
